/// Planner module — interprets user instructions and produces structured plans.
///
/// Phase 7: Uses Claude API (or compatible LLM) for intelligent plan generation.
/// Falls back to keyword matching if LLM is unavailable.
use actions::{ActionParams, ActionType};
use common::{LapisError, LapisResult};
use config::AppConfig;
use serde::{Deserialize, Serialize};

/// A single step in a plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub id: u32,
    pub action_type: ActionType,
    pub parameters: ActionParams,
    pub description: String,
    pub expected_outcome: String,
}

/// A full plan composed of ordered steps.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Plan {
    pub instruction: String,
    pub steps: Vec<PlanStep>,
    pub reasoning: Option<String>,
    pub source: PlanSource,
}

/// Whether the plan was generated by LLM or keyword fallback.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanSource {
    Llm,
    Keyword,
}

/// Creates a plan using LLM reasoning, with keyword fallback.
pub async fn create_plan(instruction: &str, config: &AppConfig, screen_context: Option<&str>) -> LapisResult<Plan> {
    // Try LLM planning if API key is configured
    if !config.reasoning_api_key.is_empty() {
        match create_plan_llm(instruction, config, screen_context).await {
            Ok(plan) => return Ok(plan),
            Err(e) => {
                eprintln!("[planner] LLM planning failed, falling back to keyword: {e}");
            }
        }
    }

    // Fallback to keyword matching
    create_plan_keyword(instruction)
}

/// Keyword-based plan generation (Phase 4 fallback).
pub fn create_plan_keyword(instruction: &str) -> LapisResult<Plan> {
    let lower = instruction.to_lowercase();
    let steps = match_instruction(&lower);

    Ok(Plan {
        instruction: instruction.to_string(),
        steps,
        reasoning: None,
        source: PlanSource::Keyword,
    })
}

// ── LLM Planning ──

const SYSTEM_PROMPT: &str = r#"You are the planning module of Lapis Sapientiae, an AI desktop automation agent for Windows.

Your job: Given a user instruction (and optionally a description of the current screen state), produce a structured JSON plan of steps to accomplish the task.

Available action types:
- MouseClick: params { x, y, button ("left"/"right") }
- MouseMove: params { x, y }
- MouseDrag: params { from_x, from_y, to_x, to_y }
- KeyboardType: params { text }
- KeyboardPress: params { key } (e.g. "Enter", "Tab", "Escape", "Backspace")
- KeyboardCombo: params { keys } (e.g. "Ctrl+S", "Alt+F4", "Win+R")
- WindowFocus: params { window_title }
- WindowMinimize: params { window_title }
- WindowMaximize: params { window_title }
- WindowClose: params { window_title }
- FileOpen: params { path }
- SystemLaunch: params { application }

Respond ONLY with valid JSON in this exact format:
{
  "reasoning": "Brief explanation of your approach",
  "steps": [
    {
      "id": 1,
      "action_type": "SystemLaunch",
      "parameters": {"application": "notepad.exe"},
      "description": "Launch Notepad",
      "expected_outcome": "Notepad window opens"
    }
  ]
}

Rules:
- Use the minimum number of steps needed
- action_type must be one of the exact types listed above
- parameters must be string key-value pairs
- If the screen context describes visible UI elements, use that information to determine coordinates
- For keyboard shortcuts, use KeyboardCombo with standard Windows shortcuts
- Be specific and practical — these steps will be executed on a real Windows desktop
- Do not include steps that require information you don't have
- If you cannot determine exact coordinates, use reasonable estimates for common UI positions"#;

/// LLM response structure.
#[derive(Deserialize)]
struct LlmPlanResponse {
    reasoning: Option<String>,
    steps: Vec<LlmPlanStep>,
}

#[derive(Deserialize)]
struct LlmPlanStep {
    id: u32,
    action_type: String,
    parameters: std::collections::HashMap<String, String>,
    description: String,
    expected_outcome: String,
}

/// Generate a plan using the configured LLM provider.
async fn create_plan_llm(
    instruction: &str,
    config: &AppConfig,
    screen_context: Option<&str>,
) -> LapisResult<Plan> {
    let user_message = if let Some(ctx) = screen_context {
        format!("Current screen state:\n{ctx}\n\nUser instruction: {instruction}")
    } else {
        format!("User instruction: {instruction}")
    };

    let (url, headers, body) = build_llm_request(config, &user_message)?;

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .build()
        .map_err(|e| LapisError::Planner(format!("HTTP client error: {e}")))?;

    let mut req = client.post(&url).json(&body);
    for (key, value) in &headers {
        req = req.header(key.as_str(), value.as_str());
    }

    println!("[planner] Sending instruction to {} ({})", config.reasoning_provider, config.reasoning_model);

    let resp = req
        .send()
        .await
        .map_err(|e| LapisError::Planner(format!("LLM request failed: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let text = resp.text().await.unwrap_or_default();
        return Err(LapisError::Planner(format!("LLM returned {status}: {text}")));
    }

    let response_text = extract_llm_response(&config.reasoning_provider, resp).await?;
    parse_llm_plan(instruction, &response_text)
}

/// Build the HTTP request for the configured LLM provider.
fn build_llm_request(
    config: &AppConfig,
    user_message: &str,
) -> LapisResult<(String, Vec<(String, String)>, serde_json::Value)> {
    match config.reasoning_provider.as_str() {
        "claude" => {
            let url = format!("{}/v1/messages", config.reasoning_endpoint.trim_end_matches('/'));
            let headers = vec![
                ("x-api-key".to_string(), config.reasoning_api_key.clone()),
                ("anthropic-version".to_string(), "2023-06-01".to_string()),
                ("content-type".to_string(), "application/json".to_string()),
            ];
            let body = serde_json::json!({
                "model": config.reasoning_model,
                "max_tokens": 2048,
                "system": SYSTEM_PROMPT,
                "messages": [
                    {"role": "user", "content": user_message}
                ]
            });
            Ok((url, headers, body))
        }
        "openai" => {
            let endpoint = if config.reasoning_endpoint.is_empty() || config.reasoning_endpoint == "https://api.anthropic.com" {
                "https://api.openai.com"
            } else {
                &config.reasoning_endpoint
            };
            let url = format!("{}/v1/chat/completions", endpoint.trim_end_matches('/'));
            let headers = vec![
                ("Authorization".to_string(), format!("Bearer {}", config.reasoning_api_key)),
                ("Content-Type".to_string(), "application/json".to_string()),
            ];
            let body = serde_json::json!({
                "model": config.reasoning_model,
                "max_tokens": 2048,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_message}
                ]
            });
            Ok((url, headers, body))
        }
        "gemini" => {
            let endpoint = if config.reasoning_endpoint.is_empty() || config.reasoning_endpoint == "https://api.anthropic.com" {
                "https://generativelanguage.googleapis.com"
            } else {
                &config.reasoning_endpoint
            };
            let url = format!(
                "{}/v1beta/models/{}:generateContent?key={}",
                endpoint.trim_end_matches('/'),
                config.reasoning_model,
                config.reasoning_api_key
            );
            let headers = vec![
                ("Content-Type".to_string(), "application/json".to_string()),
            ];
            let body = serde_json::json!({
                "systemInstruction": {"parts": [{"text": SYSTEM_PROMPT}]},
                "contents": [{"parts": [{"text": user_message}]}]
            });
            Ok((url, headers, body))
        }
        "custom" => {
            // OpenAI-compatible endpoint
            let url = format!("{}/v1/chat/completions", config.reasoning_endpoint.trim_end_matches('/'));
            let headers = vec![
                ("Authorization".to_string(), format!("Bearer {}", config.reasoning_api_key)),
                ("Content-Type".to_string(), "application/json".to_string()),
            ];
            let body = serde_json::json!({
                "model": config.reasoning_model,
                "max_tokens": 2048,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_message}
                ]
            });
            Ok((url, headers, body))
        }
        other => Err(LapisError::Planner(format!("Unknown reasoning provider: {other}"))),
    }
}

/// Extract the text response from the LLM response based on provider format.
async fn extract_llm_response(provider: &str, resp: reqwest::Response) -> LapisResult<String> {
    let raw: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| LapisError::Planner(format!("LLM response parse error: {e}")))?;

    let text = match provider {
        "claude" => {
            raw["content"]
                .as_array()
                .and_then(|arr| arr.first())
                .and_then(|block| block["text"].as_str())
                .map(|s| s.to_string())
        }
        "openai" | "custom" => {
            raw["choices"]
                .as_array()
                .and_then(|arr| arr.first())
                .and_then(|choice| choice["message"]["content"].as_str())
                .map(|s| s.to_string())
        }
        "gemini" => {
            raw["candidates"]
                .as_array()
                .and_then(|arr| arr.first())
                .and_then(|c| c["content"]["parts"].as_array())
                .and_then(|parts| parts.first())
                .and_then(|part| part["text"].as_str())
                .map(|s| s.to_string())
        }
        _ => None,
    };

    text.ok_or_else(|| LapisError::Planner(format!("Could not extract text from LLM response: {raw}")))
}

/// Parse the LLM text response into a Plan.
fn parse_llm_plan(instruction: &str, response_text: &str) -> LapisResult<Plan> {
    // The LLM might wrap JSON in markdown code blocks — strip those
    let json_str = response_text
        .trim()
        .trim_start_matches("```json")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim();

    let llm_plan: LlmPlanResponse = serde_json::from_str(json_str)
        .map_err(|e| LapisError::Planner(format!("Failed to parse LLM plan JSON: {e}\nRaw: {json_str}")))?;

    let steps: Vec<PlanStep> = llm_plan
        .steps
        .into_iter()
        .map(|s| {
            let action_type = parse_action_type(&s.action_type);
            PlanStep {
                id: s.id,
                action_type,
                parameters: s.parameters,
                description: s.description,
                expected_outcome: s.expected_outcome,
            }
        })
        .collect();

    Ok(Plan {
        instruction: instruction.to_string(),
        steps,
        reasoning: llm_plan.reasoning,
        source: PlanSource::Llm,
    })
}

/// Parse an action type string from LLM output into an ActionType enum.
fn parse_action_type(s: &str) -> ActionType {
    match s {
        "MouseClick" => ActionType::MouseClick,
        "MouseMove" => ActionType::MouseMove,
        "MouseDrag" => ActionType::MouseDrag,
        "KeyboardType" => ActionType::KeyboardType,
        "KeyboardPress" => ActionType::KeyboardPress,
        "KeyboardCombo" => ActionType::KeyboardCombo,
        "WindowFocus" => ActionType::WindowFocus,
        "WindowMinimize" => ActionType::WindowMinimize,
        "WindowMaximize" => ActionType::WindowMaximize,
        "WindowClose" => ActionType::WindowClose,
        "FileOpen" => ActionType::FileOpen,
        "SystemLaunch" => ActionType::SystemLaunch,
        _ => ActionType::SystemLaunch, // safe default
    }
}

// ── Keyword fallback (Phase 4) ──

fn match_instruction(instruction: &str) -> Vec<PlanStep> {
    if instruction.contains("notepad") {
        plan_open_notepad()
    } else if instruction.contains("calculator") || instruction.contains("calc") {
        plan_open_calculator()
    } else if instruction.contains("type") || instruction.contains("write") || instruction.contains("escribe") {
        plan_type_text(instruction)
    } else if instruction.contains("click") || instruction.contains("press") {
        plan_click()
    } else if instruction.contains("close") || instruction.contains("cerrar") {
        plan_close_window()
    } else if instruction.contains("search") || instruction.contains("buscar") || instruction.contains("find") {
        plan_search(instruction)
    } else {
        plan_generic(instruction)
    }
}

fn plan_open_notepad() -> Vec<PlanStep> {
    vec![
        PlanStep {
            id: 1,
            action_type: ActionType::SystemLaunch,
            parameters: params(&[("application", "notepad.exe")]),
            description: "Launch Notepad application".into(),
            expected_outcome: "Notepad window appears on screen".into(),
        },
        PlanStep {
            id: 2,
            action_type: ActionType::WindowFocus,
            parameters: params(&[("window_title", "Untitled - Notepad")]),
            description: "Focus the Notepad window".into(),
            expected_outcome: "Notepad window is in foreground".into(),
        },
    ]
}

fn plan_open_calculator() -> Vec<PlanStep> {
    vec![
        PlanStep {
            id: 1,
            action_type: ActionType::SystemLaunch,
            parameters: params(&[("application", "calc.exe")]),
            description: "Launch Calculator application".into(),
            expected_outcome: "Calculator window appears on screen".into(),
        },
        PlanStep {
            id: 2,
            action_type: ActionType::WindowFocus,
            parameters: params(&[("window_title", "Calculator")]),
            description: "Focus the Calculator window".into(),
            expected_outcome: "Calculator window is in foreground".into(),
        },
    ]
}

fn plan_type_text(instruction: &str) -> Vec<PlanStep> {
    let text = instruction
        .replace("type", "")
        .replace("write", "")
        .replace("escribe", "")
        .trim()
        .to_string();
    let text = if text.is_empty() { "Hello, world!".to_string() } else { text };

    vec![
        PlanStep {
            id: 1,
            action_type: ActionType::MouseClick,
            parameters: params(&[("x", "400"), ("y", "300"), ("button", "left")]),
            description: "Click on the target text area".into(),
            expected_outcome: "Text cursor appears in the target area".into(),
        },
        PlanStep {
            id: 2,
            action_type: ActionType::KeyboardType,
            parameters: params(&[("text", &text)]),
            description: format!("Type: {text}"),
            expected_outcome: "Text appears in the target area".into(),
        },
    ]
}

fn plan_click() -> Vec<PlanStep> {
    vec![PlanStep {
        id: 1,
        action_type: ActionType::MouseClick,
        parameters: params(&[("x", "500"), ("y", "400"), ("button", "left")]),
        description: "Click at target position".into(),
        expected_outcome: "Element at position is activated".into(),
    }]
}

fn plan_close_window() -> Vec<PlanStep> {
    vec![PlanStep {
        id: 1,
        action_type: ActionType::WindowClose,
        parameters: params(&[("window_title", "active")]),
        description: "Close the active window".into(),
        expected_outcome: "Active window is closed".into(),
    }]
}

fn plan_search(instruction: &str) -> Vec<PlanStep> {
    let query = instruction
        .replace("search", "")
        .replace("buscar", "")
        .replace("find", "")
        .replace("for", "")
        .trim()
        .to_string();
    let query = if query.is_empty() { "example".to_string() } else { query };

    vec![
        PlanStep {
            id: 1,
            action_type: ActionType::KeyboardCombo,
            parameters: params(&[("keys", "Win+S")]),
            description: "Open Windows search".into(),
            expected_outcome: "Windows search bar appears".into(),
        },
        PlanStep {
            id: 2,
            action_type: ActionType::KeyboardType,
            parameters: params(&[("text", &query)]),
            description: format!("Type search query: {query}"),
            expected_outcome: "Search results appear".into(),
        },
        PlanStep {
            id: 3,
            action_type: ActionType::KeyboardPress,
            parameters: params(&[("key", "Enter")]),
            description: "Press Enter to execute search".into(),
            expected_outcome: "Top search result is opened".into(),
        },
    ]
}

fn plan_generic(instruction: &str) -> Vec<PlanStep> {
    vec![PlanStep {
        id: 1,
        action_type: ActionType::SystemLaunch,
        parameters: params(&[("instruction", instruction)]),
        description: format!("Process instruction: {instruction}"),
        expected_outcome: "Instruction processed successfully".into(),
    }]
}

fn params(pairs: &[(&str, &str)]) -> ActionParams {
    pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keyword_plan_preserves_instruction() {
        let plan = create_plan_keyword("open notepad").unwrap();
        assert_eq!(plan.instruction, "open notepad");
        assert!(matches!(plan.source, PlanSource::Keyword));
    }

    #[test]
    fn notepad_plan_has_two_steps() {
        let plan = create_plan_keyword("open notepad").unwrap();
        assert_eq!(plan.steps.len(), 2);
        assert_eq!(plan.steps[0].action_type, ActionType::SystemLaunch);
    }

    #[test]
    fn parse_action_type_roundtrip() {
        assert_eq!(parse_action_type("MouseClick"), ActionType::MouseClick);
        assert_eq!(parse_action_type("KeyboardType"), ActionType::KeyboardType);
        assert_eq!(parse_action_type("SystemLaunch"), ActionType::SystemLaunch);
        assert_eq!(parse_action_type("Unknown"), ActionType::SystemLaunch);
    }

    #[test]
    fn parse_llm_plan_from_json() {
        let json = r#"{"reasoning":"test","steps":[{"id":1,"action_type":"SystemLaunch","parameters":{"application":"notepad.exe"},"description":"Open Notepad","expected_outcome":"Notepad opens"}]}"#;
        let plan = parse_llm_plan("open notepad", json).unwrap();
        assert_eq!(plan.steps.len(), 1);
        assert!(matches!(plan.source, PlanSource::Llm));
        assert_eq!(plan.reasoning.unwrap(), "test");
    }

    #[test]
    fn parse_llm_plan_strips_markdown() {
        let json = "```json\n{\"reasoning\":null,\"steps\":[{\"id\":1,\"action_type\":\"MouseClick\",\"parameters\":{\"x\":\"100\",\"y\":\"200\",\"button\":\"left\"},\"description\":\"Click\",\"expected_outcome\":\"Clicked\"}]}\n```";
        let plan = parse_llm_plan("click", json).unwrap();
        assert_eq!(plan.steps.len(), 1);
        assert_eq!(plan.steps[0].action_type, ActionType::MouseClick);
    }

    #[test]
    fn plan_is_serializable() {
        let plan = create_plan_keyword("open notepad").unwrap();
        let json = serde_json::to_string(&plan).unwrap();
        assert!(json.contains("SystemLaunch"));
        assert!(json.contains("keyword"));
    }
}
